### ISSUE TITLE
Can't get Cluster Attributes

### ISSUE THREAD

**Issue by met67** [banksy-git/lidl-gateway-freedom#17]
When I try to read an attribute (e.g. app_version from Aqara Weather sensor)
![image](https://user-images.githubusercontent.com/4471785/137087007-da799340-39ca-450e-b3b4-53ab71be2a1f.png)
I constantly get the following error in Home Assistant log:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/zha/api.py:679
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:19:53 AM (4 occurrences)
Last logged: 9:26:11 AM

[547770400288] Error handling message: Unknown error
[547681024800] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 679, in websocket_read_zigbee_cluster_attributes
    success, failure = await cluster.read_attributes(
  File "/usr/local/lib/python3.9/site-packages/zigpy/zcl/__init__.py", line 297, in read_attributes
    result = await self.read_attributes_raw(to_read, manufacturer=manufacturer)
  File "/usr/local/lib/python3.9/site-packages/zigpy/device.py", line 287, in request
    raise zigpy.exceptions.DeliveryError(
zigpy.exceptions.DeliveryError: [0x2513:1:0x0000]: Message send failure

```
Don't know if it is a problem in HA, in ZBGW or what... 😃

**Comment by MattWestb** [comment]
Your weather sensor is one sleeping end device.
Its being in deep sleep 95% of the time and then you is trying sending somthing to it it cant receiving it so ZHA getting time out / message send failure then not getting any response from it.

So you need waking it up then trying to sending somthing it  it.
Do that with pressing the small button on the over side shortly and clicking read attribute.
