### ISSUE TITLE
lidl_auskey_decode.py do not run

### ISSUE THREAD

**Issue by raveit65** [banksy-git/lidl-gateway-freedom#42]
The script always give me the error message.
```
[rave@satellite Downloads]$ python3 lidl_auskey_decode-new.py 
Enter KEK hex string line>80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFFFFFFFFFF
Encoded aus-key as hex string line 1>80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
Encoded aus-key as hex string line 2>80000010:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
Traceback (most recent call last):
  File "/home/rave/Downloads/lidl_auskey_decode-new.py", line 65, in <module>
    print("Auskey:", auskey.decode("ascii"))
                     ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
[rave@satellite Downloads]$
```
System is fedora 40 with `python3-3.12.3-2.fc40.x86_64`

I am also wondering about the output of kek and auskey in serial console.
```
<RealTek>FLR 80000000 401802 16
Flash read from 00401802 to 80000000 with 00000016 bytes	?
(Y)es , (N)o ? --> y
Flash Read Successed!
<RealTek>DW 80000000 4
80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
<RealTek>
<RealTek>FLR 80000000 402002 32
Flash read from 00402002 to 80000000 with 00000032 bytes	?
(Y)es , (N)o ? --> y
Flash Read Successed!
<RealTek>DW 80000000 8
80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
80000010:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
<RealTek>
```
I post this in public because i think the output is wrong.
Can you help me please to get the root password of my lidl gateway?

**Comment by matze20211** [comment]
Here too:

`<RealTek>FLR 80000000 401802 16                                                 
Flash read from 00401802 to 80000000 with 00000016 bytes        ?               
(Y)es , (N)o ? --> Y                                                            
Flash Read Successed!                                                           
<RealTek>DW 80000000 4                                                          
80000000:       FFFFFFFF        FFFFFFFF        FFFFFFFF        FFFFFFFF        
<RealTek>FLR 80000000 402002 32                                                 
Flash read from 00402002 to 80000000 with 00000032 bytes        ?               
(Y)es , (N)o ? --> Y                                                            
Flash Read Successed!                                                           
<RealTek>DW 80000000 8                                                          
80000000:       FFFFFFFF        FFFFFFFF        FFFFFFFF        FFFFFFFF        
80000010:       FFFFFFFF        FFFFFFFF        FFFFFFFF        FFFFFFFF `

searching for a solution i found: some using other adresses, but i dont know whre to find, here in?

` ------------------------- Force into Single IO Mode ------------------------   
|No chipID  Sft chipSize blkSize secSize pageSize sdCk opCk      chipName    |  
| 0 c84018h  0h 1000000h  10000h  10000h     100h   84    0          GD25Q128|  
 ----------------------------------------------------------------------------   
SPI flash(GD25Q128) was found at CS0, size 0x1000000                            
boot+cfg offset=0x0 size=0x20000 erasesize=0x10000                              
linux offset=0x20000 size=0x1e0000 erasesize=0x10000                            
rootfs offset=0x200000 size=0x200000 erasesize=0x10000                          
tuya-label offset=0x400000 size=0x20000 erasesize=0x10000                       
jffs2-fs offset=0x420000 size=0xbe0000 erasesize=0x10000                        
5 rtkxxpart partitions found on MTD device flash_bank_1                         
Creating 5 MTD partitions on "flash_bank_1":                                    
0x000000000000-0x000000020000 : "boot+cfg"                                      
0x000000020000-0x000000200000 : "linux"                                         
0x000000200000-0x000000400000 : "rootfs"                                        
0x000000400000-0x000000420000 : "tuya-label"                                    
0x000000420000-0x000001000000 : "jffs2-fs"             `

matze

**Comment by 0xD4M13N** [comment]
> The script always give me the error message.
> 
> ```
> [rave@satellite Downloads]$ python3 lidl_auskey_decode-new.py 
> Enter KEK hex string line>80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFFFFFFFFFF
> Encoded aus-key as hex string line 1>80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
> Encoded aus-key as hex string line 2>80000010:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
> Traceback (most recent call last):
>   File "/home/rave/Downloads/lidl_auskey_decode-new.py", line 65, in <module>
>     print("Auskey:", auskey.decode("ascii"))
>                      ^^^^^^^^^^^^^^^^^^^^^^
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xec in position 0: ordinal not in range(128)
> [rave@satellite Downloads]$
> ```
> 
> System is fedora 40 with `python3-3.12.3-2.fc40.x86_64`
> 
> I am also wondering about the output of kek and auskey in serial console.
> 
> ```
> <RealTek>FLR 80000000 401802 16
> Flash read from 00401802 to 80000000 with 00000016 bytes	?
> (Y)es , (N)o ? --> y
> Flash Read Successed!
> <RealTek>DW 80000000 4
> 80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
> <RealTek>
> <RealTek>FLR 80000000 402002 32
> Flash read from 00402002 to 80000000 with 00000032 bytes	?
> (Y)es , (N)o ? --> y
> Flash Read Successed!
> <RealTek>DW 80000000 8
> 80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
> 80000010:	FFFFFFFF	FFFFFFFF	FFFFFFFF	FFFFFFFF
> <RealTek>
> ```
> 
> I post this in public because i think the output is wrong. Can you help me please to get the root password of my lidl gateway?


It's maybe a little bit too late, but if it can help you (or somebody else), your problem is that you send each line with its address.
Your input shouldn't look like :
80000000:	FFFFFFFF	FFFFFFFF	FFFFFFFFFFFFFFFF
but :
FFFFFFFF	FFFFFFFF	FFFFFFFFFFFFFFFF

**Comment by Minothor** [comment]
Having the same issue on one of these whitelabel tuya gateways, the addresses for the KEK and the AUSKEY both return solid blocks of:
`FFFFFFFF        FFFFFFFF        FFFFFFFF        FFFFFFFF`

Leading to the tool failing as it tries to convert value 128 into ascii.

Is it possible that the addresses used are different on some versions, and if so, has anyone managed to compile a table of known addresses so far?

I'm dumping my gateways' firmwares (2 different variants of this, one branded tuya, one branded moes) but the dumping script seems to have overshot its inbuilt `0x1000000` end address default and is happily still churning through `0x09517F00` and counting, 2 days and 150MB later.

Edit: Ok, having dumped the firmware blob, and manually navigated to the offset given by the bootloader in GHex, I can now see that the Tuya-Label partition on my device appears to be completely erased - every bit from 0x400000 to 0x420000 is set. effectively my Tuya-Label partition either has no data or is only populated in memory at boot time?
